In [11]:
import numpy as np
import math

In [61]:
def MyGivenData():
    data = []
    for i in range(100):
        data.append([i, i*2])
    return np.array(data)

def DataSetDivision(data, proportion=0.3):
    train_set = []
    eval_set = []
    np.random.shuffle(data)
    length = int(data.shape[0] * proportion)
    train_set = data[: length]
    eval_set = data[length :]
    return np.array(train_set), np.array(eval_set)

def K-FoldCrossValidation(rowData, p=10, k=10):
    length = rowDdata.shape[0]
    dataIndex = list(range(length))
    dataIndex = np.split(dataIndex, k)
    ls=[]
    for i in range(k):
        train_set = dataIndex[lambda x: x!=i]
        eval_set = dataIndex[i]
        yield tarin_set, eval_set

SyntaxError: invalid syntax (<ipython-input-61-7077e2eaa65e>, line 16)

In [48]:
data = MyGivenData()
DataSetDivision(data)

(array([[ 95, 190],
        [  1,   2],
        [  4,   8],
        [ 58, 116],
        [ 44,  88],
        [ 20,  40],
        [ 12,  24],
        [ 29,  58],
        [ 52, 104],
        [  9,  18],
        [ 69, 138],
        [ 23,  46],
        [ 63, 126],
        [ 60, 120],
        [ 43,  86],
        [ 64, 128],
        [ 96, 192],
        [ 13,  26],
        [ 19,  38],
        [  0,   0],
        [ 74, 148],
        [ 91, 182],
        [ 39,  78],
        [  6,  12],
        [ 11,  22],
        [ 30,  60],
        [ 84, 168],
        [ 76, 152],
        [ 53, 106],
        [ 72, 144]]),
 array([[ 88, 176],
        [ 54, 108],
        [ 77, 154],
        [ 59, 118],
        [ 82, 164],
        [ 83, 166],
        [ 42,  84],
        [ 25,  50],
        [ 67, 134],
        [ 16,  32],
        [ 89, 178],
        [ 99, 198],
        [ 73, 146],
        [ 38,  76],
        [ 36,  72],
        [ 94, 188],
        [  5,  10],
        [ 15,  30],
        [  8,  16],
        [ 92, 184]

In [60]:
a=np.array_split(data,3)

array([[ 95, 190],
       [  1,   2],
       [  4,   8],
       [ 58, 116],
       [ 44,  88],
       [ 20,  40],
       [ 12,  24],
       [ 29,  58],
       [ 52, 104],
       [  9,  18],
       [ 69, 138],
       [ 23,  46],
       [ 63, 126],
       [ 60, 120],
       [ 43,  86],
       [ 64, 128],
       [ 96, 192],
       [ 13,  26],
       [ 19,  38],
       [  0,   0],
       [ 74, 148],
       [ 91, 182],
       [ 39,  78],
       [  6,  12],
       [ 11,  22],
       [ 30,  60],
       [ 84, 168],
       [ 76, 152],
       [ 53, 106],
       [ 72, 144],
       [ 88, 176],
       [ 54, 108],
       [ 77, 154],
       [ 59, 118]])