In [1]:
import numpy as np
import math

In [23]:
def MyGivenData():
    data = []
    for i in range(100):
        data.append([i, i*2])
    return np.array(data)

def DataSetDivision(data, proportion=0.3):
    train_set = []
    eval_set = []
    np.random.shuffle(data)
    length = int(data.shape[0] * proportion)
    train_set = data[: length]
    eval_set = data[length :]
    return np.array(train_set), np.array(eval_set)

def K_FoldCrossValidation(rowData, k=10):
    length = rowData.shape[0]
    dataIndex = np.array(range(length))
    ls = []
    np.random.shuffle(dataIndex)
    dataIndex = np.split(dataIndex, k)
    train_set = []
    eval_set = []
    for j in range(k-1):
        train_set.append(dataIndex[j])
    eval_set = dataIndex[k-1]
    return train_set, eval_set

In [24]:
data = MyGivenData()
a = K_FoldCrossValidation(data)
a

([array([28, 97, 39, 35, 19, 84,  4, 73, 83, 58]),
  array([48, 50, 85, 60, 95, 23, 26, 20, 61, 67]),
  array([ 7, 78, 15, 80, 96, 45, 87, 63, 74, 41]),
  array([62, 68,  1, 94, 12, 37, 55, 40, 33, 51]),
  array([81,  0, 99, 54, 76, 36, 34, 24,  9,  6]),
  array([22, 32, 71, 86, 47, 65, 90, 57, 10,  2]),
  array([43, 27, 93, 11, 49, 98, 16, 30, 79, 69]),
  array([29, 70, 53, 64, 42, 88,  5,  8, 92, 38]),
  array([75, 18, 14, 82, 89, 31, 66, 44, 46, 13])],
 array([ 3, 25, 56, 21, 72, 59, 17, 91, 77, 52]))

In [22]:
DataSetDivision(data)

(array([[ 45,  90],
        [ 42,  84],
        [  8,  16],
        [ 18,  36],
        [ 26,  52],
        [ 54, 108],
        [  0,   0],
        [ 48,  96],
        [ 59, 118],
        [ 72, 144],
        [ 98, 196],
        [ 56, 112],
        [ 12,  24],
        [ 49,  98],
        [ 61, 122],
        [ 78, 156],
        [ 52, 104],
        [ 19,  38],
        [ 70, 140],
        [ 82, 164],
        [ 11,  22],
        [ 30,  60],
        [ 33,  66],
        [ 69, 138],
        [ 20,  40],
        [ 60, 120],
        [ 66, 132],
        [ 77, 154],
        [ 80, 160],
        [ 99, 198]]),
 array([[  6,  12],
        [  7,  14],
        [ 74, 148],
        [ 71, 142],
        [ 75, 150],
        [  9,  18],
        [ 97, 194],
        [ 83, 166],
        [ 63, 126],
        [ 76, 152],
        [ 37,  74],
        [ 67, 134],
        [ 96, 192],
        [  5,  10],
        [ 51, 102],
        [ 92, 184],
        [ 31,  62],
        [ 38,  76],
        [ 68, 136],
        [  4,   8]