In [1]:
import numpy as np
import math

In [32]:
def MyGivenData():
    data = []
    for i in range(100):
        data.append([i, i*2])
    return np.array(data)

def DataSetDivision(data, proportion=0.3):
    train_set = []
    eval_set = []
    np.random.shuffle(data)
    length = int(data.shape[0] * proportion)
    train_set = data[: length]
    eval_set = data[length :]
    return np.array(train_set), np.array(eval_set)

def K_FoldCrossValidation(rowData, p=10, k=10):
    length = rowData.shape[0]
    dataIndex = np.array(range(length))
    ls = []
    for i in range(p):
        np.random.shuffle(dataIndex)
        dataIndex = np.split(dataIndex, k)
        print(dataIndex)
        train_set = []
        eval_set = []
        for j in range(k):
            train_set.append(dataIndex[j])
        eval_set = dataIndex[i]
        yield train_set, eval_set

In [33]:
data = MyGivenData()
a = K_FoldCrossValidation(data)
next(a)

[array([83, 90,  9, 65, 91, 72, 13, 89, 62, 66]), array([82, 12, 88, 38, 77, 29, 11, 23,  6, 32]), array([46, 50, 70, 95, 36, 31, 93, 67, 26, 81]), array([35, 97, 48, 58,  2, 87, 96, 61,  8, 99]), array([94, 40, 51,  5, 42, 47, 10, 39, 69,  7]), array([17, 57, 41, 20, 18, 49, 92, 60, 22, 25]), array([59, 15, 80,  4,  1, 34, 73, 52, 63, 68]), array([ 0, 71, 30, 24, 75, 86, 85, 84, 74, 28]), array([56, 44,  3, 33, 27, 14, 53, 78, 19, 43]), array([37, 76, 21, 45, 16, 98, 55, 79, 54, 64])]


([array([83, 90,  9, 65, 91, 72, 13, 89, 62, 66]),
  array([82, 12, 88, 38, 77, 29, 11, 23,  6, 32]),
  array([46, 50, 70, 95, 36, 31, 93, 67, 26, 81]),
  array([35, 97, 48, 58,  2, 87, 96, 61,  8, 99]),
  array([94, 40, 51,  5, 42, 47, 10, 39, 69,  7]),
  array([17, 57, 41, 20, 18, 49, 92, 60, 22, 25]),
  array([59, 15, 80,  4,  1, 34, 73, 52, 63, 68]),
  array([ 0, 71, 30, 24, 75, 86, 85, 84, 74, 28]),
  array([56, 44,  3, 33, 27, 14, 53, 78, 19, 43]),
  array([37, 76, 21, 45, 16, 98, 55, 79, 54, 64])],
 array([83, 90,  9, 65, 91, 72, 13, 89, 62, 66]))

In [48]:
data = MyGivenData()
DataSetDivision(data)

(array([[ 95, 190],
        [  1,   2],
        [  4,   8],
        [ 58, 116],
        [ 44,  88],
        [ 20,  40],
        [ 12,  24],
        [ 29,  58],
        [ 52, 104],
        [  9,  18],
        [ 69, 138],
        [ 23,  46],
        [ 63, 126],
        [ 60, 120],
        [ 43,  86],
        [ 64, 128],
        [ 96, 192],
        [ 13,  26],
        [ 19,  38],
        [  0,   0],
        [ 74, 148],
        [ 91, 182],
        [ 39,  78],
        [  6,  12],
        [ 11,  22],
        [ 30,  60],
        [ 84, 168],
        [ 76, 152],
        [ 53, 106],
        [ 72, 144]]),
 array([[ 88, 176],
        [ 54, 108],
        [ 77, 154],
        [ 59, 118],
        [ 82, 164],
        [ 83, 166],
        [ 42,  84],
        [ 25,  50],
        [ 67, 134],
        [ 16,  32],
        [ 89, 178],
        [ 99, 198],
        [ 73, 146],
        [ 38,  76],
        [ 36,  72],
        [ 94, 188],
        [  5,  10],
        [ 15,  30],
        [  8,  16],
        [ 92, 184]