In [1]:
import numpy as np
import math

In [20]:
def MyGivenData():
    data = []
    for i in range(100):
        data.append([i, i*2])
    return np.array(data)

def DataSetDivision(data, proportion=0.3):
    train_set = []
    eval_set = []
    np.random.shuffle(data)
    length = int(data.shape[0] * proportion)
    train_set = data[: length]
    eval_set = data[length :]
    return np.array(train_set), np.array(eval_set)

def K_FoldCrossValidation(rowData, k=10):
    length = rowData.shape[0]
    dataIndex = np.array(range(length))
    ls = []
    np.random.shuffle(dataIndex)
    dataIndex = np.split(dataIndex, k)
    train_set = []
    eval_set = []
    for j in range(k-1):
        train_set.append(dataIndex[j])
    eval_set = dataIndex[k-1]
    return train_set, eval_set

In [21]:
data = MyGivenData()
a = K_FoldCrossValidation(data)
a

[array([71, 40, 74, 54, 63, 64, 65, 66, 28, 47]), array([72,  3, 38, 55, 76, 16, 41,  0, 82, 44]), array([81, 13, 34, 83, 14, 29, 68, 52,  1,  7]), array([53, 57, 49, 86, 24, 20, 18, 91, 45, 85]), array([33, 56, 32, 10, 37, 12, 75, 93, 22, 19]), array([95, 21,  5, 67, 98, 77, 36, 84,  6, 27]), array([23,  8, 25, 17, 59, 79, 62,  9, 50, 78]), array([90, 94, 73, 43, 51, 89, 42, 26, 70, 96]), array([87, 92, 99, 35, 39, 11, 61, 97, 58, 69]), array([30, 31, 15,  4, 80, 60, 88,  2, 48, 46])]


([array([71, 40, 74, 54, 63, 64, 65, 66, 28, 47]),
  array([72,  3, 38, 55, 76, 16, 41,  0, 82, 44]),
  array([81, 13, 34, 83, 14, 29, 68, 52,  1,  7]),
  array([53, 57, 49, 86, 24, 20, 18, 91, 45, 85]),
  array([33, 56, 32, 10, 37, 12, 75, 93, 22, 19]),
  array([95, 21,  5, 67, 98, 77, 36, 84,  6, 27]),
  array([23,  8, 25, 17, 59, 79, 62,  9, 50, 78]),
  array([90, 94, 73, 43, 51, 89, 42, 26, 70, 96]),
  array([87, 92, 99, 35, 39, 11, 61, 97, 58, 69])],
 array([30, 31, 15,  4, 80, 60, 88,  2, 48, 46]))

In [22]:
DataSetDivision(data)

(array([[ 45,  90],
        [ 42,  84],
        [  8,  16],
        [ 18,  36],
        [ 26,  52],
        [ 54, 108],
        [  0,   0],
        [ 48,  96],
        [ 59, 118],
        [ 72, 144],
        [ 98, 196],
        [ 56, 112],
        [ 12,  24],
        [ 49,  98],
        [ 61, 122],
        [ 78, 156],
        [ 52, 104],
        [ 19,  38],
        [ 70, 140],
        [ 82, 164],
        [ 11,  22],
        [ 30,  60],
        [ 33,  66],
        [ 69, 138],
        [ 20,  40],
        [ 60, 120],
        [ 66, 132],
        [ 77, 154],
        [ 80, 160],
        [ 99, 198]]),
 array([[  6,  12],
        [  7,  14],
        [ 74, 148],
        [ 71, 142],
        [ 75, 150],
        [  9,  18],
        [ 97, 194],
        [ 83, 166],
        [ 63, 126],
        [ 76, 152],
        [ 37,  74],
        [ 67, 134],
        [ 96, 192],
        [  5,  10],
        [ 51, 102],
        [ 92, 184],
        [ 31,  62],
        [ 38,  76],
        [ 68, 136],
        [  4,   8]